const testVariables = {
  userId: 'user_id',
  commonKeyId: 'common_key_id',
  clientId: 'partner_id#client',
  partnerId: 'partner_id',
  clientSecret: 'client_secret',
  wrongClientSecret: 'wrong_client_secret',
  secondUserId: 'second_user_id',
  documentId: 'document_id',
  recordId: 'record_id',
  fileId: 'file_id',
  tresorId: 'tresor_id',
  sessionId: 'session_id',
  regValidationVerifier: 'reg_validation_verifier',
  operationId: 'operation_id',
  userAlias: 'user@alias.de',
  password: 'password',
  wrongPassword: 'wrong_password',
  dateString: '2017-12-15',
  dateTimeString: '2017-12-15T10:35:52.492',
  tag: 'resourceType=documentReference',
  secondTag: 'partner=1',
  updatedByPartnerTag: 'updatedbypartner=2',
  encodedTag: 'client=ann%5Fotation',
  customTag: 'custom=annotation',
  customAppDataFlag: 'custom=flag%3Dappdata',
  encryptedTag: 'encrypted_tag',
  tek: 'tag_encryption_key',
  encryptedTek: 'encrypted_tag_encryption_key',
  encryptedUserData: 'encrypted_user_data',
  string: 'string',
  encryptedString: 'encrypted_string',
  state: 'state',
  userData: {},
  refreshToken: 'refresh_token',
  appId: 'app_id',
  annotation: 'annotation',
  invalidAnnotation:
    'khjghghghdgjfhdsgfhdgsfjsfsfgdufsdyfyyujjtgfyyyyfyuyyyryrygugydrdfgugrssfdcbterwddzczxczcxk' +
    'khjghghghdgjfhdsgfhdgsfjsfsfgdufsdyfyyujjtgfyyyyfyuyyyryrygugydrdfgugrssfdcbterwddzczxczcxkigyfjhfdsfsdfsdfsd' +
    'khjghghghdgjfhdsgfhdgsfjsfsfgdufsdyfyyujjtgfyyyyfyuyyyryrygug',
  dataModelVersion: 99,
};

export default testVariables;
